name: flutter_application_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  animated_splash_screen: ^1.3.0
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.3.0
  http: ^1.1.2
  image_cropper: ^5.0.1
  image_picker: ^1.0.5
  path_provider: ^2.0.11
  shared_preferences: ^2.1.2
  sqflite: ^2.2.2
  url_launcher: ^6.1.7
  webview_flutter: ^4.4.2
  youtube_player_flutter: ^8.1.1

flutter:
  uses-material-design: true
